### ISSUE TITLE
Could you tell the meaning of variable n_drugdrug_rel_types in main.py?

### ISSUE THREAD

**Issue by Msan1995** [marinkaz/decagon#5]
Could you tell the meaning of variable n_drugdrug_rel_types in main.py?

**Comment by vidarmehr** [comment]
I think it is the number of polypharmacy side effects (or type of edges in drug-drug network). In the paper, they say there have focused on predicting the 964 polypharmacy side effects that each occurred in at least 500 drug combinations.

**Comment by Msan1995** [comment]
I think so too, wanted to confirm. Thank you for the answer

**Comment by Msan1995** [comment]
Do you know how to run the code with the original dataset?

**Comment by vidarmehr** [comment]
No problem! 

Not yet. I am working on it. I think we just need to create adjacency matrices for the protein-protein network as well as protein-drug network and create a list of adjacency matrices for each edge type in drug-drug network.
